### ISSUE TITLE
Windows Defender detects this as a Trojan and prevents me from downloading.

### ISSUE THREAD

**Issue by Jenrikku** [FuryBaguette/SwitchLayoutEditor#14] opened 2020-09-20 11:53 UTC
![**Screenshot**](https://user-images.githubusercontent.com/60291632/93710639-9b4db680-fb48-11ea-9c39-fbe8ea41aec5.png)

**Comment by exelix11** [comment] 2020-09-21 13:39
Huh, this is weird. For me it's detected as `Trojan:Win32/Zpevdo.B` which from a quick google search seems to be linked a lot with false positives. I must have changed something that triggers AI detection.
Interestingly, it's something that happened recently as even the original exe in my build folder is now getting flagged, while a week ago when i ulploaded it here defender didn't complain.

It seems [beta 10 is not getting flagged](https://www.virustotal.com/gui/file/6606dd4e326dbe2d13897be964117b08bda685a1a0bf0f67d7117c959d080aec/detection), [beta 11 for comparison](https://www.virustotal.com/gui/file/f00a219daf92db616e0c7ca5dc85114b9a367d0e21431c65a9646d8a0db554de/detection)

[These](https://github.com/FuryBaguette/SwitchLayoutEditor/compare/beta10...master) are all the changes i made to the code, maybe some of the new class names, will have to do some trial and error. There are more changes in the SwitchThemesCommon library but that's part of the new theme injector release as well and doesn't seem to get detected so i assume that's not the problem.

Will look into it and post updates here, in case it makes you feel safer you can use the previous version as it's not being detected.

**Comment by exelix11** [comment] 2020-09-21 13:57
So like, i've just requested virustotal to re-analyze beta 10 and 8 AVs flag it now, previous analysis was from 4 months ago.

**Comment by exelix11** [comment] 2020-09-21 14:02
Just changed some class names in the code and it brought down the number of detections of latest versions from 12 to 8, which is the same as previous version.
Something weird i noticed is that defender is not really confident about it being a virus, eg double clicking the exe shows defender virus warning, right click and analyze gives nothing.

**Comment by exelix11** [comment] 2020-09-21 19:00
The problem has been reported to the Windows Defender team and they confirmed it's an error and removed the detection from the database, as soon as you update the antivirus database it shouldn't complain anymore, If you confirm it works now i'll close this.

**Comment by Jenrikku** [comment] 2020-09-21 19:07
I can confirm that it works. My browser lets download it without problems.

**Comment by elisha1099** [comment] 2021-02-23 00:28
This is happening to me too, beta 13 gets detected while downloading and beta 12 gets detected when I open it.

**Comment by exelix11** [comment] 2021-02-23 10:02
Yeah can confirm, they use some kind of AI to detect viruses and feel this is gonna get flagged every once in a while forever probably. I'll make another false positive report for latest release and let you know the result.

**Comment by exelix11** [comment] 2021-02-23 18:50
MS confirmed it's a false positive and removed the detection, if you update defender definitions it should let you download and use it.

**Closed by exelix11** 2021-02-23 18:50 UTC

**Comment by Marin37** [comment] 2021-02-27 21:01
Hello there, I just wanted to note that McAfee also detects a false positive, as `GenericRXNQ-RE!14B60347F2E3`, probably for the same reason as defender...
Still, It let's me restore the file and "risky" run it anyways.

(It's on spanish btw)
![Captura de pantalla 2021-02-27 175727](https://user-images.githubusercontent.com/57327931/109400064-49922f00-7925-11eb-94de-a36b0f0157dd.png)

**Comment by exelix11** [comment] 2021-02-28 09:04
Unfortunatly i don't know why this keeps on happening and can't really report it to all AV vendors, i'll just stick with defender cause it's the one most peple use, also when defender whitelists it it seems to reduce the overall detections on virustotal so maybe soon enough mcafee will remove the detection as well ? Idk.
Guess if you want to help check if there's an option like "report as not malware" or something like that.

**Comment by Eds1989** [comment] 2021-08-21 14:39
Sadly I am trying to download the release from two days ago, and Defender (In IE, Edge and Chrome) is detecting this as a virus.

**Comment by impeeza** [comment] 2021-09-27 04:10
I know is a closed issue but today (september 26th 2021)  boot Firefox as windows defender detect the download as a virus:
Firefox:
![image](https://user-images.githubusercontent.com/41979604/134844138-ffd3bb46-aa0f-499b-b8a5-d67bc226480b.png)
![image](https://user-images.githubusercontent.com/41979604/134844193-797bed0e-4b73-4c9e-a6ca-0c394fa93e9c.png)


Windows Defender:
![image](https://user-images.githubusercontent.com/41979604/134844154-00fcea6b-9edc-4eb0-8d4f-49f6f005eb72.png)
![image](https://user-images.githubusercontent.com/41979604/134844223-1ebe6927-149d-47eb-b5b0-6e8f89b12760.png)

It's weird.

**Comment by Bakuya** [comment] 2021-10-07 08:37
I can also confirm that on release 14 both firefox and windows defender detect this as malware

**Comment by MetaMysteries8** [comment] 2022-11-15 03:02
this happened to me when downloading from github for some reason, but it never happens from any other sites, could github be infected?
